### ISSUE TITLE
Pretrained weights

### ISSUE THREAD

**Issue by patrickvonplaten** [AkariAsai/evidentiality_qa#1]
Hey, 

This looks like a super cool model. Are you planning on releasing the fine-tuned weights for the model as well?

**Comment by AkariAsai** [comment]
Thank you for your interest in our work! Yes, we are planning to release the fine-tuned model weights as well.

**Comment by AkariAsai** [comment]
Hi. we have updated the codebase and you can download the fine-tuned models [here](https://drive.google.com/drive/folders/17TjyGIccUsm09RHheI0-4eKJqRQd1ATb?usp=sharing).
Please see the detailed instructions at [README.md](https://github.com/AkariAsai/evidentiality_qa/README.md)

**Comment by patrickvonplaten** [comment]
Very cool! Thanks. We can try to add the model to `transformers` and to make a nice demo on Hugging Face Spaces if you'd like. 

Opened a feature request here: https://github.com/huggingface/transformers/issues/15387

**Comment by AkariAsai** [comment]
Thank you for the update!
